[package]
name = "app"
version = "0.1.0"
authors = ["Matthias Devlamynck <matthias.devlamynck@mailoo.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstr = "0.2.8"
qmetaobject = "0.2.3"
